// xstate-react/src/components/RandomCat/index.tsx
import { useMachine } from "@xstate/react";
import { RandomCatMachine } from "./machine";

export const RandomCat = () => {
  const [current, send] = useMachine(RandomCatMachine);
  const { image } = current.context;

  return (
    <div>
      <h3>Current State: {(current.value as String).toUpperCase()}</h3>
      <button onClick={() => send("FETCH")}>Get Image</button>
      <div>
        {image && (
          <img
            src={image}
            alt={"cat_gif"}
            style={{ width: "500px", height: "auto" }}
          />
        )}
      </div>
    </div>
  );
};

// xstate-vue/src/components/RandomCat/index.vue
<template>
  <div>
    <h3>Current State: {{ current }}</h3>
    <button @click="fetching">Get Image</button>
    <div>
      <img v-if="imageCat" :src="imageCat" alt="cat_gif" />
    </div>
  </div>
</template>

<script lang="ts">
import { useMachine } from "@xstate/vue";
import { RandomCatMachine } from "./machine";
import { computed } from "@vue/reactivity";

export default {
  setup() {
    const { state, send } = useMachine(RandomCatMachine);

    const fetching = () => send("FETCH");

    const imageCat = computed(() => state.value.context.image);

    return {
      imageCat,
      current: computed(() => String(state.value.value).toUpperCase()),
      send,
      fetching,
    };
  },
};
</script>
