// xstate-vue/src/components/LightBulp/index.vue
<template>
  <div>
    <h3>Current State: {{ current }}</h3>
    <button @click="onToggle('TOGGLE')">Switch</button>
    <div>
      <img
        v-if="isOn"
        src="https://img.icons8.com/material-outlined/100/000000/light-on--v2.png"
      />
      <img
        v-if="isOff"
        src="https://img.icons8.com/material-rounded/100/000000/light-off.png"
      />
    </div>
  </div>
</template>
<script lang="ts">
import { computed } from "@vue/reactivity";
import { useMachine } from "@xstate/vue";
import { LightBulpMachine } from "./machine";

export default {
  setup() {
    const { state, send } = useMachine(LightBulpMachine);

    const isOn = computed(() => state.value.matches("on"));
    const isOff = computed(() => state.value.matches("off"));

    const onToggle = (value) => send(value);

    return {
      current: computed(() => String(state.value.value).toUpperCase()),
      isOn,
      isOff,
      onToggle,
    };
  },
};
</script>

// xstate-react/src/components/LightBulp/index.tsx
import { useMachine } from "@xstate/react";
import { LightBulpMachine } from "./machine";

export function LightBulp() {
  const [current, send] = useMachine(LightBulpMachine);

  return (
    <div>
      <h3>Current State: {(current.value as String).toUpperCase()}</h3>
      <button onClick={() => send("TOGGLE")}>Switch</button>
      <div>
        {current.matches("on") && (
          <img src="https://img.icons8.com/material-outlined/100/000000/light-on--v2.png" />
        )}
        {current.matches("off") && (
          <img src="https://img.icons8.com/material-rounded/100/000000/light-off.png" />
        )}
      </div>
    </div>
  );
}
